# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/workspace

    docker:
      - image: circleci/php:7.4-fpm-node-browsers
        environment:
          APP_DEBUG: true
          APP_ENV: testing
          APP_KEY: base64:Dummy6uH3OUb3hxN+PAiJKlC+EGZ2KYi8VHxsfdJpLk=
          DB_CONNECTION: circleci
      - image: circleci/postgres:9.6.9-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circleci_test

    steps:
      # Checkout source
      - checkout

      # Install Container modules
      - run:
          name: install packages
          command: |
            sudo apt update
            sudo apt-get install -y libonig-dev libpq-dev
            sudo docker-php-ext-install pdo_pgsql

      # Install PHP modules
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "./src/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: composer install
          working_directory: ./src
          command: |
            mv ../vendor ./
            php ./composer.phar install
      - save_cache:
          key: v1-dependencies-{{ checksum "./src/composer.json" }}
          paths:
            - ./src/vendor

      # Install Node modules
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./src/package.json" }}
            - node-v1-
      - run:
          name: yarn install
          working_directory: ./src
          command: |
            mv ../node_modules ./
            yarn install
      - save_cache:
          key: node-v1-{{ checksum "./src/package.json" }}
          paths:
            - ./src/node_modules

      # setup database
      - run:
          name: setup database
          working_directory: ./src
          command: |
            php artisan migrate
            php artisan db:seed

      # run test
      - run:
          name: run test
          working_directory: ./src
          command: |
            ./vendor/bin/phpunit

  deploy:
    working_directory: ~/workspace
    docker:
      - image: buildpack-deps:trusty
    steps:
      # Checkout source
      - checkout

      # Deploy
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  release:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
